# Generated by Django 4.1.5 on 2023-01-03 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_cartoonifier_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserCartoonify',
        ),
    ]
